### ISSUE TITLE
Support for Symfony 6 and php 8.1

### ISSUE THREAD

**Issue by madmortigan1** [ancyrweb/TaskSchedulerBundle#44]
Hello,

Will there be an upgrade that support upgrading to Symfony 6 with php 8.1 ?
In case there is, is there a timeframe ?

Thank you,

**Comment by NicoHaase** [comment]
Thanks for asking - the new version 0.10.0 should handle that now

**Comment by madmortigan1** [comment]
Thank you very much for the fast update.
